### ISSUE TITLE
Are you doing ok nope?

### ISSUE THREAD

**Issue by fardaxx38** [nopeless/nopeless#1]
You don't seem to be doing alright, it even seems you're idealizing about suicide. I'm very worried. If anything is wrong please go seek professional help or contact me if you want to talk about it

**Comment by nopeless** [comment]
@fardaxx38 Thoughts r just thoughts

I am safe, even though I'm going through a lot

Think of it like getting a surgery. It hurts, but you know it will get better and you have hope

I am just letting my feelings go for the first time. I have stopped thinking in certain bad ways. These are the last screams of it. The reason I put it here is so maybe others going through similar emotions can explore better. After all, just hiding these emotions is worse.

I do understand that these texts are violent in nature. It's supposed to be that way. But they aren't cries for help.

I hope you are doing well as well. I'll come back one day and explain everything :>

**Comment by fardaxx38** [comment]
Stay safe nope
